name: 'Deploy API SushiStorage'

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
   deploy:
     runs-on: 'ubuntu-latest'

     steps:
     - uses: 'actions/checkout@v3'
     - run : echo deploy API SushiStorage
